/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,
  assetPrefix: process.env.BASE_PATH || '',
  basePath: process.env.BASE_PATH || '',
  reactStrictMode: false,
  compress: true,
  poweredByHeader: false,
  productionBrowserSourceMaps: false,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cms.fieldcamp.ai",
      },
      {
        protocol: "https",
        hostname: "demo.fieldcamp.ai",
      },
    ],
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    minimumCacheTTL: 31536000,
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains'
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN'
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff'
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin'
          },
          {
            key: 'Permissions-Policy',
            value: 'geolocation=(), microphone=(), camera=(), payment=(self "https://calendly.com")'
          },
          // {
          //   key: 'Content-Security-Policy',
          //   value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://www.gstatic.com https://www.google.com https://www.youtube.com https://assets.calendly.com https://calendly.com https://connect.facebook.net https://widget.intercom.io https://js.intercomcdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.cdnfonts.com https://assets.calendly.com https://calendly.com https://js.intercomcdn.com; img-src 'self' data: blob: https: http:; font-src 'self' data: https://fonts.gstatic.com https://fonts.cdnfonts.com https://dev5.spaceto.in https://assets.calendly.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://api.vercel.com https://calendly.com https://api.calendly.com https://www.facebook.com https://api-iam.intercom.io https://api.intercom.io https://api-ping.intercom.io https://nexus-websocket-a.intercom.io https://uploads.intercomcdn.com https://uploads.intercomusercontent.com; frame-src https: http: 'self'; object-src 'self'; base-uri 'self'; form-action 'self'; media-src 'self' https: http:;"
          // }
        ]
      }
    ]; 
  },
  rewrites: async () => [{
    source: "/sitemap-:post_type.xml",
    destination: "/sitemap.xml/:post_type",
  },],
  redirects: async () => [
    { source: '/crm/roofing/', destination: '/industries/roofing/', permanent: true },
    { source: '/crm/window-cleaning/', destination: '/industries/window-cleaning/', permanent: true },
    { source: '/crm/pest-control/', destination: '/industries/pest-control/', permanent: true },
    { source: '/crm/snow-removal/', destination: '/industries/snow-removal/', permanent: true },
    { source: '/crm/remodeling/', destination: '/industries/remodeling/', permanent: true },
    { source: '/crm/property-maintainence/', destination: '/industries/property-maintainence/', permanent: true },
    { source: '/crm/janitorial/', destination: '/industries/janitorial/', permanent: true },
    { source: '/crm/junk-removal/', destination: '/industries/junk-removal/', permanent: true },
    { source: '/crm/lawn-care/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/crm/landscaping/', destination: '/industries/landscaping/', permanent: true },
    { source: '/crm/fencing/', destination: '/industries/fencing/', permanent: true },
    { source: '/crm/flooring/', destination: '/industries/flooring/', permanent: true },
    { source: '/crm/paving/', destination: '/industries/paving/', permanent: true },
    { source: '/crm/plumbers/', destination: '/industries/plumbers/', permanent: true },
    { source: '/crm/electrician/', destination: '/industries/electrician/', permanent: true },
    { source: '/crm/handyman/', destination: '/industries/handyman/', permanent: true },
    { source: '/crm/excavation/', destination: '/industries/excavation/', permanent: true },
    { source: '/crm/installation/', destination: '/industries/installation/', permanent: true },
    { source: '/crm/hvac/', destination: '/industries/hvac/', permanent: true },
    { source: '/crm/cleaning-business/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/crm/construction/', destination: '/industries/construction/', permanent: true },
    { source: '/crm/painting-contractors/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/crm/garage-door/', destination: '/industries/garage-door/', permanent: true },
    { source: '/crm/appliance-repair/', destination: '/industries/appliance-repair/', permanent: true },
    // { source: '/why-fieldcamp/', destination: '/about/', permanent: true },
    { source: '/industries/window-cleaning-software/', destination: '/industries/window-cleaning/', permanent: true },
    { source: '/industries/tree-care-software/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/features/crm', destination: '/features/ai-crm', permanent: true },
    { source: '/download/', destination: '/welcome/', permanent: true },
    { source: '/blog/window-cleaning-business-plan/', destination: '/industries/window-cleaning/', permanent: true },
    { source: '/blog/why-service-company-is-not-growing/', destination: '/welcome/', permanent: true },
    { source: '/blog/why-is-estimating-important-for-businesses/', destination: '/welcome/', permanent: true },
    { source: '/blog/what-is-post-construction-cleaning/', destination: '/industries/construction/', permanent: true },
    { source: '/blog/what-do-landscapers-do-in-the-winter/', destination: '/industries/landscaping/', permanent: true },
    { source: '/blog/types-of-plumbing-services/', destination: '/welcome/', permanent: true },
    { source: '/blog/types-of-cleaning-services/', destination: '/welcome/', permanent: true },
    { source: '/blog/tree-service-marketing-ideas/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/tree-service-business-plan/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/thank-you-notes-for-customers/', destination: '/welcome/', permanent: true },
    { source: '/blog/snow-removal-pricing-formula/', destination: '/industries/snow-removal/', permanent: true },
    { source: '/blog/snow-removal-hacks/', destination: '/welcome/', permanent: true },
    { source: '/blog/snow-removal-contract/', destination: '/welcome/', permanent: true },
    { source: '/blog/snow-removal-advertising-ideas/', destination: '/industries/snow-removal/', permanent: true },
    { source: '/blog/service-contract-management/', destination: '/welcome/', permanent: true },
    { source: '/blog/septic-tank-business-tips/', destination: '/welcome/', permanent: true },
    { source: '/blog/seasonal-business-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/profitable-painting-business-ideas/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/blog/professional-painting-tips-and-tricks/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/blog/pricing-strategies-for-service-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/pool-service-marketing/', destination: '/welcome/', permanent: true },
    { source: '/blog/plumbing-van-organization-set-up-ideas/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumbing-sales-tips/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumbing-safety-tips/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumbing-pricing-manual-guide/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumbing-marketing-ideas/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumbing-leads/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumbing-business-ideas/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumbing-ads/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumber-salary/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/plumber-certification/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/pest-control-technician-salary/', destination: '/industries/pest-control/', permanent: true },
    { source: '/blog/pest-control-sales/', destination: '/industries/pest-control/', permanent: true },
    { source: '/blog/pest-control-marketing-strategies/', destination: '/industries/pest-control/', permanent: true },
    { source: '/blog/pest-control-business-plan/', destination: '/industries/pest-control/', permanent: true },
    { source: '/blog/painting-business-plan/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/blog/painting-business-names/', destination: '/welcome/', permanent: true },
    { source: '/blog/new-plumbing-technology/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/blog/new-hvac-technology/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/locksmith-business-plan/', destination: '/welcome/', permanent: true },
    { source: '/blog/lawn-care-tools-and-equipment/', destination: '/welcome/', permanent: true },
    { source: '/blog/lawn-care-profit-margin/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/lawn-care-pricing-chart/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/lawn-care-marketing/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/lawn-care-maintenance-tips/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/lawn-care-job-description/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/lawn-care-contract/', destination: '/welcome/', permanent: true },
    { source: '/blog/lawn-care-business-tips-tricks-secrets/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/lawn-care-business-names/', destination: '/welcome/', permanent: true },
    { source: '/blog/landscaping-services-list/', destination: '/welcome/', permanent: true },
    { source: '/blog/landscaping-business-plan/', destination: '/industries/landscaping/', permanent: true },
    { source: '/blog/landscaping-business-names/', destination: '/industries/landscaping/', permanent: true },
    { source: '/blog/how-to-write-cleaning-services-business-plan/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-get-lawn-care-customers-fast/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-get-hvac-leads/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/how-to-get-hvac-certified/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/how-to-get-commercial-lawn-accounts/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-generate-electrical-leads/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/how-to-franchise-a-service-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-estimate-fence-cost/', destination: '/industries/fencing/', permanent: true },
    { source: '/blog/how-to-estimate-electrical-work/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/how-to-estimate-a-painting-job/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/blog/how-to-create-successful-hvac-business-plan/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/how-to-create-lawn-care-business-plan/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-create-cleaning-business-proposal/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/how-to-become-field-service-engineer/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-become-field-service-director/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-become-construction-estimator/', destination: '/industries/construction/', permanent: true },
    { source: '/blog/how-to-become-an-arborist/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-become-an-appliance-repair-technician/', destination: '/industries/appliance-repair/', permanent: true },
    { source: '/blog/how-to-become-a-handyman/', destination: '/industries/handyman/', permanent: true },
    { source: '/blog/how-much-to-charge-for-house-cleaning/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/house-cleaning-business-checklist/', destination: '/welcome/', permanent: true },
    { source: '/blog/home-service-business-marketing/', destination: '/welcome/', permanent: true },
    { source: '/blog/home-service-business-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/home-maintenance-contracts-guide/', destination: '/welcome/', permanent: true },
    { source: '/blog/home-depot-desk-vs-lowes-desk/', destination: '/welcome/', permanent: true },
    { source: '/blog/handyman-skills/', destination: '/industries/handyman/', permanent: true },
    { source: '/blog/handyman-services-price-list/', destination: '/welcome/', permanent: true },
    { source: '/blog/handyman-services-list/', destination: '/welcome/', permanent: true },
    { source: '/blog/handyman-marketing-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/handyman-business-names/', destination: '/welcome/', permanent: true },
    { source: '/blog/handyman-business-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/handyman-advertising-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/general-contractor-markup/', destination: '/welcome/', permanent: true },
    { source: '/blog/garage-door-marketing-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/field-service-technician-salary/', destination: '/welcome/', permanent: true },
    { source: '/blog/field-service-technician-job-description/', destination: '/welcome/', permanent: true },
    { source: '/blog/field-service-manager-salary-responsibilities-skills/', destination: '/welcome/', permanent: true },
    { source: '/blog/field-service-management-books/', destination: '/welcome/', permanent: true },
    { source: '/blog/field-service-engineer-vs-field-service-technician/', destination: '/welcome/', permanent: true },
    { source: '/blog/estimate-disclaimer/', destination: '/welcome/', permanent: true },
    { source: '/blog/emerging-and-innovative-hvac-industry-trends/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/electrician-van-setup-organization-ideas/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrician-salary/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrician-marketing-strategies/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrician-job-description/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrician-interview-questions/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrical-pricing-book/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrical-contractor-salary/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrical-contractor-marketing-strategies/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrical-contracting-business-plan/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/electrical-business-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/customer-experience-best-practices/', destination: '/welcome/', permanent: true },
    { source: '/blog/contractor-business-names/', destination: '/welcome/', permanent: true },
    { source: '/blog/construction-cost-estimating/', destination: '/industries/construction/', permanent: true },
    { source: '/blog/company-cancellation-policy-with-examples/', destination: '/welcome/', permanent: true },
    { source: '/blog/cleaning-supplies-for-business-checklist/', destination: '/welcome/', permanent: true },
    { source: '/blog/cleaning-business-names/', destination: '/welcome/', permanent: true },
    { source: '/blog/cleaning-business-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/carpet-cleaning-marketing-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/carpet-cleaning-business-plan/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/carpet-cleaning-business-equipment/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/carpentry-business-names/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-plumbing-websites/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/best-plumbing-tools/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-garage-door-tools/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-field-service-management-software-for-businesses/', destination: '/', permanent: true },
    { source: '/blog/best-essential-hvac-tools/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/best-electrician-tools/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-electrician-blogs/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/best-electric-pressure-washers/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-chimney-cleaning-tools/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-appliance-repair-tools/', destination: '/industries/appliance-repair/', permanent: true },
    { source: '/blog/benefits-of-field-service-management-software-for-businesses/', destination: '/welcome/', permanent: true },
    { source: '/blog/benefits-of-digital-transformation-in-field-service/', destination: '/welcome/', permanent: true },
    { source: '/blog/benefits-of-app-for-handyman-services/', destination: '/industries/handyman/', permanent: true },
    { source: '/blog/appointment-reminder-templates/', destination: '/welcome/', permanent: true },
    { source: '/blog/appliance-repair-leads/', destination: '/industries/appliance-repair/', permanent: true },
    { source: '/blog/annual-maintenance-contract/', destination: '/welcome/', permanent: true },
    { source: '/industries/trash-bin-cleaning-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/snow-removal-software/', destination: '/industries/snow-removal/', permanent: true },
    { source: '/industries/roofing-software/', destination: '/industries/roofing/', permanent: true },
    { source: '/industries/property-maintenance-software/', destination: '/industries/property-maintainence/', permanent: true },
    { source: '/industries/pressure-washing-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/pool-service-software/', destination: '/industries/', permanent: true },
    { source: '/industries/plumbing-software/', destination: '/industries/plumbers/', permanent: true },
    { source: '/industries/pest-control-software/', destination: '/industries/pest-control/', permanent: true },
    { source: '/industries/painting-contractor-management-software/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/industries/maintenance-repair-business-software/', destination: '/industries/property-maintainence/', permanent: true },
    { source: '/industries/locksmith-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/lawn-care-software/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/industries/landscaping-business-software/', destination: '/industries/landscaping/', permanent: true },
    { source: '/industries/junk-removal-software/', destination: '/industries/junk-removal/', permanent: true },
    { source: '/industries/hvac-software/', destination: '/industries/hvac/', permanent: true },
    { source: '/industries/handyman-software/', destination: '/industries/handyman/', permanent: true },
    { source: '/industries/garage-door-software/', destination: '/industries/garage-door/', permanent: true },
    { source: '/industries/furniture-assembly-business-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/fence-software/', destination: '/industries/fencing/', permanent: true },
    { source: '/industries/elevator-service-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/electrical-contracting-software/', destination: '/industries/electrician/', permanent: true },
    { source: '/industries/construction-management-software/', destination: '/industries/construction/', permanent: true },
    { source: '/industries/cleaning-business-software/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/industries/chimney-sweep-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/carpet-cleaning-software/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/industries/carpenter-business-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/boat-detailing-cleaning-software/', destination: '/industries/appliance-repair/', permanent: true },
    { source: '/industries/appliance-repair-software/', destination: '/welcome/', permanent: true },
    { source: '/industries/alarm-system-installation-software/', destination: '/industries/', permanent: true },
    { source: '/guides/service-pricing/', destination: '/welcome/', permanent: true },
    { source: '/guides/plumbing-business/', destination: '/industries/plumbers/', permanent: true },
    { source: '/guides/lawn-care-business/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/guides/hvac-business/', destination: '/industries/hvac/', permanent: true },
    { source: '/guides/field-service-business/', destination: '/welcome/', permanent: true },
    { source: '/guides/cleaning-business/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/guides/business-startup/', destination: '/welcome/', permanent: true },
    { source: '/features/job-scheduling-for-field-service/', destination: '/welcome/', permanent: true },
    { source: '/features/job-dispatching-for-field-service/', destination: '/welcome/', permanent: true },
    { source: '/features/create-invoices-for-field-service/', destination: '/welcome/', permanent: true },
    { source: '/features/analytical-reports-for-field-service/', destination: '/crm/', permanent: true },
    { source: '/features/accept-online-payment-for-field-service/', destination: '/welcome/', permanent: true },
    { source: '/blog/plumber-cerficiation/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/best-window-washing-tools/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-snow-removal-tools/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-scheduling-software-for-cleaning-services/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/best-scheduling-apps-for-businesses/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-rugged-tablets-for-service-technicians/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-referral-program-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-pool-cleaning-equipment/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-plumbing-gloves/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-plumbing-blogs/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/best-pest-control-apps/', destination: '/industries/pest-control/', permanent: true },
    { source: '/blog/best-painting-tools-list/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-on-demand-handyman-apps/', destination: '/industries/handyman/', permanent: true },
    { source: '/blog/best-marketing-strategies-for-contractors/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-lead-generation-companies-for-contractors/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-landscaping-tools/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-irrigation-tools-list/', destination: '/welcome/', permanent: true },
    { source: '/blog/best-hvac-books/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/best-hvac-blogs/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/landscaping-business-name-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/landscaping-business-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/landscape-business-marketing-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/job-sheets/', destination: '/welcome/', permanent: true },
    { source: '/blog/iot-field-services/', destination: '/welcome/', permanent: true },
    { source: '/blog/hvac-van-setup-organization-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/hvac-technician-tips/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-technician-salary/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-slow-season/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-sales-tips/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-safety-tips/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-pricing-guide/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-marketing-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/hvac-management/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-maintenance-tips-to-avoid-expensive-repairs/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-invoices-templates/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-insurance/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-industry-challenges-and-solution/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-franchise-guide/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-customer-service-ideas/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-contract/', destination: '/welcome/', permanent: true },
    { source: '/blog/hvac-business-management-tips/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/hvac-business-ideas/', destination: '/welcome/', permanent: true },
    { source: '/blog/hvac-branding-strategies/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/how-to-write-cleaning-services-business-plan/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-an-hvac-business/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/how-to-start-an-electrical-business/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/how-to-start-an-appliance-repair-business/', destination: '/industries/appliance-repair/', permanent: true },
    { source: '/blog/how-to-start-a-window-cleaning-business/', destination: '/industries/window-cleaning/', permanent: true },
    { source: '/blog/how-to-start-a-tree-service/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-start-a-snow-removal-business/', destination: '/industries/snow-removal/', permanent: true },
    { source: '/blog/how-to-start-a-service-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-sanitizing-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-roof-cleaning-business/', destination: '/industries/roofing/', permanent: true },
    { source: '/blog/how-to-start-a-pressure-washing-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-pool-cleaning-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-plumbing-business/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/how-to-start-a-pest-control-business/', destination: '/industries/pest-control/', permanent: true },
    { source: '/blog/how-to-start-a-painting-business/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/blog/how-to-start-a-lawn-care-business/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-start-a-landscaping-business/', destination: '/industries/landscaping/', permanent: true },
    { source: '/blog/how-to-start-a-junk-removal-business/', destination: '/industries/junk-removal/', permanent: true },
    { source: '/blog/how-to-start-a-home-service-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-holiday-lighting-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-handyman-business/', destination: '/industries/handyman/', permanent: true },
    { source: '/blog/how-to-start-a-gutter-cleaning-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-general-contracting-business/', destination: '/industries/construction/', permanent: true },
    { source: '/blog/how-to-start-a-garage-door-business/', destination: '/industries/garage-door/', permanent: true },
    { source: '/blog/how-to-start-a-furniture-assembly-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-fencing-business/', destination: '/industries/fencing/', permanent: true },
    { source: '/blog/how-to-start-a-chimney-sweep-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-start-a-carpet-cleaning-business/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/how-to-start-a-carpentry-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-run-an-irrigation-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-run-a-service-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-run-a-lawn-care-business/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-recruit-hvac-technicians/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/how-to-price-pressure-washing-jobs/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-price-landscaping-job/', destination: '/industries/landscaping/', permanent: true },
    { source: '/blog/how-to-price-a-job-as-a-contractor/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-price-a-commercial-cleaning-job/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/how-to-market-cleaning-service-business/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/how-to-market-a-painting-business/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/blog/how-to-make-money-in-construction/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-increase-hvac-business-owner-salary-revenue/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-increase-revenue-from-existing-customers/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-improve-hvac-business-profit-margins/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-hire-lawn-care-employees/', destination: '/industries/lawn-care/', permanent: true },
    { source: '/blog/how-to-hire-cleaners/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-grow-your-electrical-business/', destination: '/industries/electrician/', permanent: true },
    { source: '/blog/how-to-grow-plumbing-business/', destination: '/industries/plumbers/', permanent: true },
    { source: '/blog/how-to-grow-hvac-business/', destination: '/industries/hvac/', permanent: true },
    { source: '/blog/how-to-grow-cleaning-business/', destination: '/industries/cleaning-business/', permanent: true },
    { source: '/blog/how-to-grow-a-fencing-business/', destination: '/industries/fencing/', permanent: true },
    { source: '/blog/how-to-grow-a-carpentry-business/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-get-pressure-washing-jobs/', destination: '/welcome/', permanent: true },
    { source: '/blog/how-to-get-painting-contracts/', destination: '/industries/painting-contractors/', permanent: true },
    { source: '/reviews/jobber-reviews/', destination: '/reviews/jobber/', permanent: true },
    { source: '/reviews/workwave-reviews/', destination: '/reviews/workwave/', permanent: true },
    { source: '/reviews/synchroteam-reviews/', destination: '/reviews/synchroteam/', permanent: true },
    { source: '/reviews/servicetitan-reviews/', destination: '/reviews/servicetitan/', permanent: true },
    { source: '/reviews/servicemax-reviews/', destination: '/reviews/servicemax/', permanent: true },
    { source: '/reviews/service-fusion-reviews/', destination: '/reviews/service-fusion/', permanent: true },
    { source: '/reviews/mhelpdesk-reviews/', destination: '/reviews/mhelpdesk/', permanent: true },
    { source: '/reviews/housecall-pro-reviews/', destination: '/reviews/housecall-pro/', permanent: true },
    { source: '/reviews/fieldpoint-reviews/', destination: '/reviews/fieldpoint/', permanent: true },
    { source: '/reviews/fieldedge-reviews/', destination: '/reviews/fieldedge/', permanent: true },
  ]
}

module.exports = nextConfig; 

